[project]
name = "typst-anki"
version = "0.1.0"
description = "Typst Math within Anki flashcards"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aqt>=24.11",
    "pypandoc>=1.15",
    "pyqt6>=6.8.0",
    "ruff>=0.9.3",
    "typst>=0.12.3",
]
